config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/users/show', to: 'users#show'
  get '/workouts/today', to: 'workouts#today'
  get '/workouts/week', to: 'workouts#week'
  resources :workouts
  root to: "workouts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :workouts
end

app/models/workout.rb
class Workout < ApplicationRecord
  validates :type_workout, :calories, :duration, :presence => true
  belongs_to :user

  scope :this_weeks_workouts, -> { where("DATE(created_at) > ?", (Date.today).to_time - 7.days) }
  scope :todays_workouts, -> { where("DATE(created_at) > ?", (Date.today).to_time - 1.days) }

  def self.total_calories
    calories = 0
    Workout.all.each do |workout|
      calories+= workout.calories
    end
    calories
  end

  def self.total_duration
    duration = 0
    Workout.all.each do |workout|
      duration+= workout.duration
    end
    duration
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /workouts
  # GET /workouts.json
  def index
    @workouts = Workout.all
  end

  def today
    @workouts = Workout.where(user_id: current_user.id).todays_workouts
    render :index
  end

  def week
    @workouts = Workout.where(user_id: current_user.id).this_weeks_workouts
    render :index
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(workout_params)
    current_user.workouts << @workout

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1
  # PATCH/PUT /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout.destroy
    respond_to do |format|
      format.html { redirect_to workouts_url, notice: 'Workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workout_params
      params.require(:workout).permit(:type_workout, :duration, :calories, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CardioTracker</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
      <% if user_signed_in? %>
      <nav class="navbar sticky-top navbar-expand-sm navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="/users/show"> Your Account </a>
            <a class="nav-item nav-link" href="/workouts/today"> Today's Workouts </a>
            <a class="nav-item nav-link" href="/workouts/week"> This Week's Workouts </a>
            <a class="nav-item nav-link" href="/workouts"> All Workouts </a>
            <a class="nav-item nav-link" href="/workouts/new"> Create Workout </a>
            <p class="nav-item nav-link"><%= link_to("Sign Out", destroy_user_session_path, :method => 'delete', class: "btn btn-primary", role: "button") %><p>
          </div>
        </div>
      </nav>

        <% else %>
        <nav class="navbar sticky-top navbar-expand-sm navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <p class="nav-item nav-link"><%= link_to("Sign Up", new_user_registration_path, class: "btn btn-primary", role: "button") %></p>
              <p class="nav-item nav-link"><%= link_to('Login', new_user_session_path, class: "btn btn-primary", role: "button")  %></p>
            </div>
          </div>
        </nav>
      <%end %>
      <br>
      <div class="container">
    <%= content_tag(:div, flash[:error], :id => "flash_error", class: "alert alert-danger alert-dismissable", data: { dismiss: 'alert' }) if flash[:error] %>
    <%= content_tag(:div, flash[:notice], :id => "flash_notice", class: "alert alert-success alert-dismissable", data: { dismiss: 'alert' }) if flash[:notice] %>
    <%= content_tag(:div, flash[:alert], :id => "flash_alert", class: "alert alert-danger alert-dismissable", data: { dismiss: 'alert' }) if flash[:alert] %>
    <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/show.html.erb
<h3>Signed in as: <%= @user.email %></h3>
<h5>Total Workouts Created: <%= @user.workouts.count %></h5>

app/views/workouts/_form.html.erb
<%= form_with(model: workout, local: true) do |form| %>
  <% if workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% workout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :type_workout, id: :workout_type, class: "form-control", placeholder: "Type" %>
  </div>

  <div class="form-group">
    <%= form.number_field :duration, id: :workout_duration, class: "form-control", placeholder: "Duration" %>
  </div>

  <div class="form-group">
    <%= form.number_field :calories, id: :workout_calories, class: "form-control", placeholder: "Calories Burned" %>
  </div>

  <div class="actions">
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
  <br>
<% end %>

app/views/workouts/edit.html.erb
<h1>Editing Workout</h1>

<%= render 'form', workout: @workout %>

<%= link_to 'Show', @workout, class: "btn btn-primary", role: "button" %>
<%= link_to 'Back', workouts_path, class: "btn btn-primary", role: "button" %>

app/views/workouts/index.html.erb
<h1>Workouts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Type</th>
      <th>Duration</th>
      <th>Calories</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <td><%= workout.type_workout %></td>
        <td><%= workout.duration %></td>
        <td><%= workout.calories %></td>
        <td><%= link_to 'Show', workout, class: "btn btn-primary", role: "button" %></td>
        <td><%= link_to 'Edit', edit_workout_path(workout), class: "btn btn-primary", role: "button" %></td>
        <td><%= link_to 'Delete', workout, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary", role: "button" %></td>
      </tr>
    <% end %>
    <tr>
        <td>Totals</td>
        <td><%= @workouts.total_calories %></td>
        <td><%= @workouts.total_duration %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
  </tbody>
</table>

<br>

<%= link_to 'New Workout', new_workout_path, class: "btn btn-primary", role: "button" %>

app/views/workouts/new.html.erb
<h1>New Workout</h1>

<%= render 'form', workout: @workout %>

<%= link_to 'Back', workouts_path, class: "btn btn-primary", role: "button" %>

app/views/workouts/show.html.erb
<p class="col-sm-10 row">
  <strong class="col-sm-3 row">Type:</strong>
  <%= @workout.type_workout %>
</p>

<p class="col-sm-10 row">
  <strong class="col-sm-3 row">Duration:</strong>
  <%= @workout.duration %>
</p>

<p class="col-sm-10 row">
  <strong class="col-sm-3 row">Calories:</strong>
  <%= @workout.calories %>
</p>

<p class="col-sm-10 row">
  <strong class="col-sm-3 row">User:</strong>
  <%= @workout.user_id %>
</p>

<%= link_to 'Edit', edit_workout_path(@workout), class: "btn btn-primary", role: "button" %>
<%= link_to 'Back', workouts_path, class: "btn btn-primary", role: "button" %>